# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bed2fc155e824d2c3479966786002d33efc23bd99cd453a7e6802ed3b31d0c03226fda88ceef274b7d6c24cf91aaf55d982080861d82c5e99e91aa54d73f586

test:
  secret_key_base: 2a43f9d0e7738f1112036071b8062aba3e554fcbc85139d2025b703b6ebe3b306b99d95c48bbf22abd2572d42b14e90d66c9deae12a3d1e90a4e42624a9b796a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
